# Generated by Django 5.2.17 on 2026-09-29 05:34

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletledgerentry',
            options={'ordering': ('created_at', 'id')},
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='walletledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('initial_credit', 'Initial credit'), ('reservation', 'Usage reservation'), ('usage_debit', 'Settled usage'), ('release', 'Reservation release'), ('refund', 'Refund')], max_length=32),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New conversation', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI-compatible'), ('anthropic', 'Anthropic-compatible'), ('google', 'Google-compatible')], max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UsageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI-compatible'), ('anthropic', 'Anthropic-compatible'), ('google', 'Google-compatible')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed_before_upstream', 'Failed before upstream'), ('reconciliation_required', 'Reconciliation required')], default='pending', max_length=32)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reserved_micro_usd', models.PositiveBigIntegerField(default=0)),
                ('charge_micro_usd', models.PositiveBigIntegerField(default=0)),
                ('pricing_version', models.CharField(default='flat-2-micro-usd-per-token-v1', max_length=64)),
                ('upstream_request_id', models.CharField(blank=True, max_length=128)),
                ('reconciliation_reason', models.CharField(blank=True, choices=[('usage_unknown', 'Usage unknown'), ('reservation_exceeded', 'Reservation exceeded')], max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_request', to='chat.message')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_requests', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='chat.usagerequest'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner', '-updated_at'], name='conversation_owner_updated'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at', 'id'], name='message_conversation_order'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider__isnull', True), ('role', 'user')), models.Q(('provider__isnull', False), ('role', 'assistant')), _connector='OR'), name='message_provider_matches_role'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='message_content_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_usage_idempotency_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_tokens__isnull', True), ('output_tokens__isnull', True), ('total_tokens__isnull', True)), models.Q(('input_tokens__isnull', False), ('output_tokens__isnull', False), ('total_tokens', django.db.models.expressions.CombinedExpression(models.F('input_tokens'), '+', models.F('output_tokens')))), _connector='OR'), name='usage_token_counts_consistent'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), models.Q(('input_tokens__isnull', False), ('output_tokens__isnull', False), ('total_tokens__isnull', False)), _connector='OR'), name='successful_usage_has_token_counts'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reconciliation_reason__isnull', False), ('status', 'reconciliation_required')), models.Q(models.Q(('status', 'reconciliation_required'), _negated=True), ('reconciliation_reason__isnull', True)), _connector='OR'), name='usage_reconciliation_reason_matches_status'),
        ),
    ]
