# Generated by Django 5.2.17 on 2026-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_walletledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletledgerentry',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('wallet', 'idempotency_key'), name='unique_wallet_ledger_idempotency'),
        ),
    ]
