# Generated by Django 5.2.17 on 2026-09-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_walletledgerentry_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_provider_matches_role',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider__isnull', True), ('role', 'user')), models.Q(('provider__in', ['openai', 'anthropic', 'google']), ('provider__isnull', False), ('role', 'assistant')), _connector='OR'), name='message_provider_matches_role'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='usage_idempotency_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['openai', 'anthropic', 'google'])), name='usage_provider_is_supported'),
        ),
    ]
