# Generated by Django 5.2.17 on 2026-09-29 05:55

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_message_provider_matches_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerequest',
            name='reserved_input_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerequest',
            name='reserved_output_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerequest',
            name='reserved_total_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walletledgerentry',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='chat.usagerequest'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reserved_input_tokens__isnull', True), ('reserved_output_tokens__isnull', True), ('reserved_total_tokens__isnull', True)), models.Q(('reserved_input_tokens__isnull', False), ('reserved_output_tokens__isnull', False), ('reserved_total_tokens', django.db.models.expressions.CombinedExpression(models.F('reserved_input_tokens'), '+', models.F('reserved_output_tokens')))), _connector='OR'), name='reserved_token_caps_consistent'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('reserved', 'succeeded', 'reconciliation_required')), _negated=True), models.Q(('reserved_input_tokens__isnull', False), ('reserved_output_tokens__isnull', False), ('reserved_total_tokens__isnull', False)), _connector='OR'), name='reserved_usage_has_token_caps'),
        ),
    ]
