# Generated by Django 5.2.17 on 2026-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_usagerequest_reserved_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'reserved', 'succeeded', 'failed_before_upstream', 'reconciliation_required'))), name='usage_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(('reconciliation_reason__isnull', True), ('reconciliation_reason__in', ('usage_unknown', 'reservation_exceeded')), _connector='OR'), name='usage_reconciliation_reason_supported'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ('initial_credit', 'reservation', 'usage_debit', 'release', 'refund'))), name='wallet_ledger_entry_type_supported'),
        ),
    ]
