# Generated by Django 5.2.17 on 2026-09-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usagerequest_usage_status_supported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerequest',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_requests', to='chat.conversation'),
        ),
    ]
