# Generated by Django 5.2.17 on 2026-09-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_usagerequest_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerequest',
            name='assistant_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_request', to='chat.message'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), ('assistant_message__isnull', False), _connector='OR'), name='successful_usage_has_assistant_message'),
        ),
    ]
