# Generated by Django 5.2.17 on 2026-09-29 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_usagerequest_assistant_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerequest',
            name='user_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_usage_request', to='chat.message'),
        ),
    ]
