# Generated by Django 5.2.17 on 2026-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_usagerequest_user_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usagerequest',
            name='reserved_usage_has_token_caps',
        ),
        migrations.RemoveConstraint(
            model_name='usagerequest',
            name='usage_status_supported',
        ),
        migrations.RemoveConstraint(
            model_name='walletledgerentry',
            name='wallet_ledger_entry_type_supported',
        ),
        migrations.AlterField(
            model_name='usagerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed_before_upstream', 'Failed before upstream'), ('reconciliation_required', 'Reconciliation required'), ('reconciled_released', 'Reconciled and released')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='walletledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('initial_credit', 'Initial credit'), ('reservation', 'Usage reservation'), ('usage_debit', 'Settled usage'), ('release', 'Reservation release'), ('refund', 'Refund'), ('admin_credit', 'Administrative credit'), ('admin_debit', 'Administrative debit')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'reserved', 'succeeded', 'failed_before_upstream', 'reconciliation_required', 'reconciled_released'))), name='usage_status_supported'),
        ),
        migrations.AddConstraint(
            model_name='usagerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('reserved', 'succeeded', 'reconciliation_required', 'reconciled_released')), _negated=True), models.Q(('reserved_input_tokens__isnull', False), ('reserved_output_tokens__isnull', False), ('reserved_total_tokens__isnull', False)), _connector='OR'), name='reserved_usage_has_token_caps'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ('initial_credit', 'reservation', 'usage_debit', 'release', 'refund', 'admin_credit', 'admin_debit'))), name='wallet_ledger_entry_type_supported'),
        ),
    ]
