# Generated by Django 5.2.17 on 2026-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_usagerequest_reserved_usage_has_token_caps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerequest',
            name='latency_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
