"""
Django settings for allchat_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEVELOPMENT_SECRET_KEY = 'insecure-local-development-only'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', _DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes'}
if not DEBUG and SECRET_KEY == _DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when DEBUG is disabled.')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat.apps.ChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'allchat_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'allchat_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()
if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        }
    }
elif DB_ENGINE in {'postgres', 'postgresql'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'allchat'),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    raise ImproperlyConfigured('DB_ENGINE must be sqlite or postgresql.')

PROXY_BASE_URL = os.getenv('PROXY_BASE_URL', 'https://proxy.litechat.ai').rstrip('/')
OPENAI_PROXY_KEY = os.getenv('OPENAI_PROXY_KEY', '')
ANTHROPIC_PROXY_KEY = os.getenv('ANTHROPIC_PROXY_KEY', '')
GOOGLE_PROXY_KEY = os.getenv('GOOGLE_PROXY_KEY', '')
OPENAI_PROXY_MODEL = os.getenv('OPENAI_PROXY_MODEL', 'gpt-5.6-luna')
ANTHROPIC_PROXY_MODEL = os.getenv('ANTHROPIC_PROXY_MODEL', 'claude-haiku-4-5-20251001')
GOOGLE_PROXY_MODEL = os.getenv('GOOGLE_PROXY_MODEL', 'gemini-3.8-flash')
PROXY_CONNECT_TIMEOUT = int(os.getenv('PROXY_CONNECT_TIMEOUT', '5'))
PROXY_READ_TIMEOUT = int(os.getenv('PROXY_READ_TIMEOUT', '60'))

if not DEBUG:
    missing_proxy_keys = [
        key_name
        for key_name in ('OPENAI_PROXY_KEY', 'ANTHROPIC_PROXY_KEY', 'GOOGLE_PROXY_KEY')
        if not os.getenv(key_name)
    ]
    if missing_proxy_keys:
        raise ImproperlyConfigured(
            f"Missing required provider configuration: {', '.join(missing_proxy_keys)}."
        )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'chat.User'
LOGIN_URL = 'chat:login'
LOGIN_REDIRECT_URL = 'chat:home'
LOGOUT_REDIRECT_URL = 'chat:login'
